
package org.soaplab.morphosintactic_tagging.freeling3_tagging;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "freeling3_taggingService", targetNamespace = "http://soaplab.org/morphosintactic_tagging/freeling3_tagging", wsdlLocation = "http://ws04.iula.upf.edu/soaplab2-axis/typed/services/morphosintactic_tagging.freeling3_tagging?wsdl")
public class Freeling3TaggingService
    extends Service
{

    private final static URL FREELING3TAGGINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException FREELING3TAGGINGSERVICE_EXCEPTION;
    private final static QName FREELING3TAGGINGSERVICE_QNAME = new QName("http://soaplab.org/morphosintactic_tagging/freeling3_tagging", "freeling3_taggingService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ws04.iula.upf.edu/soaplab2-axis/typed/services/morphosintactic_tagging.freeling3_tagging?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FREELING3TAGGINGSERVICE_WSDL_LOCATION = url;
        FREELING3TAGGINGSERVICE_EXCEPTION = e;
    }

    public Freeling3TaggingService() {
        super(__getWsdlLocation(), FREELING3TAGGINGSERVICE_QNAME);
    }

    public Freeling3TaggingService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FREELING3TAGGINGSERVICE_QNAME, features);
    }

    public Freeling3TaggingService(URL wsdlLocation) {
        super(wsdlLocation, FREELING3TAGGINGSERVICE_QNAME);
    }

    public Freeling3TaggingService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FREELING3TAGGINGSERVICE_QNAME, features);
    }

    public Freeling3TaggingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Freeling3TaggingService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Freeling3Tagging
     */
    @WebEndpoint(name = "freeling3_taggingPort")
    public Freeling3Tagging getFreeling3TaggingPort() {
        return super.getPort(new QName("http://soaplab.org/morphosintactic_tagging/freeling3_tagging", "freeling3_taggingPort"), Freeling3Tagging.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Freeling3Tagging
     */
    @WebEndpoint(name = "freeling3_taggingPort")
    public Freeling3Tagging getFreeling3TaggingPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soaplab.org/morphosintactic_tagging/freeling3_tagging", "freeling3_taggingPort"), Freeling3Tagging.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FREELING3TAGGINGSERVICE_EXCEPTION!= null) {
            throw FREELING3TAGGINGSERVICE_EXCEPTION;
        }
        return FREELING3TAGGINGSERVICE_WSDL_LOCATION;
    }

}
