
package org.soaplab.text_mining.kwic;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "kwicService", targetNamespace = "http://soaplab.org/text_mining/kwic", wsdlLocation = "http://ws04.iula.upf.edu/soaplab2-axis/typed/services/text_mining.kwic?wsdl")
public class KwicService
    extends Service
{

    private final static URL KWICSERVICE_WSDL_LOCATION;
    private final static WebServiceException KWICSERVICE_EXCEPTION;
    private final static QName KWICSERVICE_QNAME = new QName("http://soaplab.org/text_mining/kwic", "kwicService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ws04.iula.upf.edu/soaplab2-axis/typed/services/text_mining.kwic?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        KWICSERVICE_WSDL_LOCATION = url;
        KWICSERVICE_EXCEPTION = e;
    }

    public KwicService() {
        super(__getWsdlLocation(), KWICSERVICE_QNAME);
    }

    public KwicService(WebServiceFeature... features) {
        super(__getWsdlLocation(), KWICSERVICE_QNAME, features);
    }

    public KwicService(URL wsdlLocation) {
        super(wsdlLocation, KWICSERVICE_QNAME);
    }

    public KwicService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, KWICSERVICE_QNAME, features);
    }

    public KwicService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KwicService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Kwic
     */
    @WebEndpoint(name = "kwicPort")
    public Kwic getKwicPort() {
        return super.getPort(new QName("http://soaplab.org/text_mining/kwic", "kwicPort"), Kwic.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Kwic
     */
    @WebEndpoint(name = "kwicPort")
    public Kwic getKwicPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soaplab.org/text_mining/kwic", "kwicPort"), Kwic.class, features);
    }

    private static URL __getWsdlLocation() {
        if (KWICSERVICE_EXCEPTION!= null) {
            throw KWICSERVICE_EXCEPTION;
        }
        return KWICSERVICE_WSDL_LOCATION;
    }

}
